#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Planty"
  https://create.arduino.cc/cloud/things/b476add1-fca1-4c79-8ac1-0d616531c7f9 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int humidityValue;
  int soilValue;
  int tempValue;
  bool ledSwitch;
  bool startPump;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  pinMode(BUILTIN_LED, OUTPUT);
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  tempValue = random(0,500);
  humidityValue = random(0,100);
  soilValue = random(0,1000);
  delay(500);
}



/*
  Since StartPump is READ_WRITE variable, onStartPumpChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onStartPumpChange()  {
  // Add your code here to act upon StartPump change
  if (startPump){
    digitalWrite(BUILTIN_LED,HIGH);
  } else {
    digitalWrite(BUILTIN_LED,LOW);
  }
}




/*
  Since LedSwitch is READ_WRITE variable, onLedSwitchChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedSwitchChange()  {
  // Add your code here to act upon LedSwitch change
  if (ledSwitch){
    digitalWrite(BUILTIN_LED,HIGH);
  } else {
    digitalWrite(BUILTIN_LED,LOW);
  }
}

